//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type GetProvider {
  GetProvider(id: String, api_key: String, base_url: String, model: String)
}

pub fn get_provider() {
  let sql =
    "
SELECT id, api_key, base_url, model
FROM providers
LIMIT 1"
  #(sql, [], get_provider_decoder())
}

pub fn get_provider_decoder() -> decode.Decoder(GetProvider) {
  use id <- decode.field(0, decode.string)
  use api_key <- decode.field(1, decode.string)
  use base_url <- decode.field(2, decode.string)
  use model <- decode.field(3, decode.string)
  decode.success(GetProvider(id:, api_key:, base_url:, model:))
}

pub fn save_provider() {
  let sql = "DELETE FROM providers"
  #(sql, [])
}

pub fn insert_provider(
  id id: String,
  api_key api_key: String,
  base_url base_url: String,
  model model: String,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO providers (id, api_key, base_url, model, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(api_key),
    dev.ParamString(base_url),
    dev.ParamString(model),
    dev.ParamInt(created_at),
    dev.ParamInt(updated_at),
  ])
}

pub type ListAgents {
  ListAgents(id: String, name: String, status: String, actor_hash: String)
}

pub fn list_agents() {
  let sql =
    "
SELECT id, name, status, actor_hash
FROM agents
ORDER BY updated_at DESC"
  #(sql, [], list_agents_decoder())
}

pub fn list_agents_decoder() -> decode.Decoder(ListAgents) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use status <- decode.field(2, decode.string)
  use actor_hash <- decode.field(3, decode.string)
  decode.success(ListAgents(id:, name:, status:, actor_hash:))
}

pub type GetAgent {
  GetAgent(
    id: String,
    name: String,
    description: String,
    chute_source: String,
    actor_hash: String,
    status: String,
  )
}

pub fn get_agent(id id: String) {
  let sql =
    "SELECT id, name, description, chute_source, actor_hash, status
FROM agents
WHERE id = ?"
  #(sql, [dev.ParamString(id)], get_agent_decoder())
}

pub fn get_agent_decoder() -> decode.Decoder(GetAgent) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use description <- decode.field(2, decode.string)
  use chute_source <- decode.field(3, decode.string)
  use actor_hash <- decode.field(4, decode.string)
  use status <- decode.field(5, decode.string)
  decode.success(GetAgent(
    id:,
    name:,
    description:,
    chute_source:,
    actor_hash:,
    status:,
  ))
}

pub type GetAgentByName {
  GetAgentByName(
    id: String,
    name: String,
    description: String,
    chute_source: String,
    actor_hash: String,
    status: String,
  )
}

pub fn get_agent_by_name(name name: String) {
  let sql =
    "SELECT id, name, description, chute_source, actor_hash, status
FROM agents
WHERE name = ?"
  #(sql, [dev.ParamString(name)], get_agent_by_name_decoder())
}

pub fn get_agent_by_name_decoder() -> decode.Decoder(GetAgentByName) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use description <- decode.field(2, decode.string)
  use chute_source <- decode.field(3, decode.string)
  use actor_hash <- decode.field(4, decode.string)
  use status <- decode.field(5, decode.string)
  decode.success(GetAgentByName(
    id:,
    name:,
    description:,
    chute_source:,
    actor_hash:,
    status:,
  ))
}

pub fn insert_agent(
  id id: String,
  name name: String,
  description description: String,
  chute_source chute_source: String,
  actor_hash actor_hash: String,
  status status: String,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO agents (id, name, description, chute_source, actor_hash, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(name),
    dev.ParamString(description),
    dev.ParamString(chute_source),
    dev.ParamString(actor_hash),
    dev.ParamString(status),
    dev.ParamInt(created_at),
    dev.ParamInt(updated_at),
  ])
}

pub fn update_agent_status(
  status status: String,
  updated_at updated_at: Int,
  id id: String,
) {
  let sql =
    "UPDATE agents SET status = ?, updated_at = ?
WHERE id = ?"
  #(sql, [
    dev.ParamString(status),
    dev.ParamInt(updated_at),
    dev.ParamString(id),
  ])
}

pub type GetAgentHandlers {
  GetAgentHandlers(effect_name: String, handler_name: String)
}

pub fn get_agent_handlers(agent_id agent_id: String) {
  let sql =
    "
SELECT effect_name, handler_name
FROM agent_handlers
WHERE agent_id = ?"
  #(sql, [dev.ParamString(agent_id)], get_agent_handlers_decoder())
}

pub fn get_agent_handlers_decoder() -> decode.Decoder(GetAgentHandlers) {
  use effect_name <- decode.field(0, decode.string)
  use handler_name <- decode.field(1, decode.string)
  decode.success(GetAgentHandlers(effect_name:, handler_name:))
}

pub fn insert_agent_handler(
  id id: String,
  agent_id agent_id: String,
  effect_name effect_name: String,
  handler_name handler_name: String,
  created_at created_at: Int,
) {
  let sql =
    "INSERT INTO agent_handlers (id, agent_id, effect_name, handler_name, created_at)
VALUES (?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(agent_id),
    dev.ParamString(effect_name),
    dev.ParamString(handler_name),
    dev.ParamInt(created_at),
  ])
}

pub type ListSkills {
  ListSkills(
    id: String,
    name: String,
    description: String,
    tags: String,
    status: String,
  )
}

pub fn list_skills() {
  let sql =
    "
SELECT id, name, description, tags, status
FROM skills
WHERE status = 'active'
ORDER BY updated_at DESC"
  #(sql, [], list_skills_decoder())
}

pub fn list_skills_decoder() -> decode.Decoder(ListSkills) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use description <- decode.field(2, decode.string)
  use tags <- decode.field(3, decode.string)
  use status <- decode.field(4, decode.string)
  decode.success(ListSkills(id:, name:, description:, tags:, status:))
}

pub type GetSkill {
  GetSkill(
    id: String,
    name: String,
    description: String,
    chute_source: String,
    tags: String,
    status: String,
  )
}

pub fn get_skill(id id: String) {
  let sql =
    "SELECT id, name, description, chute_source, tags, status
FROM skills
WHERE id = ?"
  #(sql, [dev.ParamString(id)], get_skill_decoder())
}

pub fn get_skill_decoder() -> decode.Decoder(GetSkill) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use description <- decode.field(2, decode.string)
  use chute_source <- decode.field(3, decode.string)
  use tags <- decode.field(4, decode.string)
  use status <- decode.field(5, decode.string)
  decode.success(GetSkill(
    id:,
    name:,
    description:,
    chute_source:,
    tags:,
    status:,
  ))
}

pub type GetSkillByName {
  GetSkillByName(
    id: String,
    name: String,
    description: String,
    chute_source: String,
    tags: String,
    status: String,
  )
}

pub fn get_skill_by_name(name name: String) {
  let sql =
    "SELECT id, name, description, chute_source, tags, status
FROM skills
WHERE name = ?"
  #(sql, [dev.ParamString(name)], get_skill_by_name_decoder())
}

pub fn get_skill_by_name_decoder() -> decode.Decoder(GetSkillByName) {
  use id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use description <- decode.field(2, decode.string)
  use chute_source <- decode.field(3, decode.string)
  use tags <- decode.field(4, decode.string)
  use status <- decode.field(5, decode.string)
  decode.success(GetSkillByName(
    id:,
    name:,
    description:,
    chute_source:,
    tags:,
    status:,
  ))
}

pub fn insert_skill(
  id id: String,
  name name: String,
  description description: String,
  chute_source chute_source: String,
  tags tags: String,
  status status: String,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO skills (id, name, description, chute_source, tags, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(name),
    dev.ParamString(description),
    dev.ParamString(chute_source),
    dev.ParamString(tags),
    dev.ParamString(status),
    dev.ParamInt(created_at),
    dev.ParamInt(updated_at),
  ])
}

pub fn update_skill(
  description description: String,
  chute_source chute_source: String,
  tags tags: String,
  updated_at updated_at: Int,
  id id: String,
) {
  let sql =
    "UPDATE skills SET description = ?, chute_source = ?, tags = ?, updated_at = ?
WHERE id = ?"
  #(sql, [
    dev.ParamString(description),
    dev.ParamString(chute_source),
    dev.ParamString(tags),
    dev.ParamInt(updated_at),
    dev.ParamString(id),
  ])
}

pub fn deactivate_skill(updated_at updated_at: Int, id id: String) {
  let sql =
    "UPDATE skills SET status = 'inactive', updated_at = ?
WHERE id = ?"
  #(sql, [dev.ParamInt(updated_at), dev.ParamString(id)])
}

pub type ListActiveSchedules {
  ListActiveSchedules(
    id: String,
    agent_id: Option(String),
    skill_id: String,
    cron_expr: String,
    status: String,
    last_fired_at: Option(Int),
    next_fire_at: Int,
  )
}

pub fn list_active_schedules() {
  let sql =
    "
SELECT id, agent_id, skill_id, cron_expr, status, last_fired_at, next_fire_at
FROM schedules
WHERE status = 'active'
ORDER BY next_fire_at ASC"
  #(sql, [], list_active_schedules_decoder())
}

pub fn list_active_schedules_decoder() -> decode.Decoder(ListActiveSchedules) {
  use id <- decode.field(0, decode.string)
  use agent_id <- decode.field(1, decode.optional(decode.string))
  use skill_id <- decode.field(2, decode.string)
  use cron_expr <- decode.field(3, decode.string)
  use status <- decode.field(4, decode.string)
  use last_fired_at <- decode.field(5, decode.optional(decode.int))
  use next_fire_at <- decode.field(6, decode.int)
  decode.success(ListActiveSchedules(
    id:,
    agent_id:,
    skill_id:,
    cron_expr:,
    status:,
    last_fired_at:,
    next_fire_at:,
  ))
}

pub type GetSchedule {
  GetSchedule(
    id: String,
    agent_id: Option(String),
    skill_id: String,
    cron_expr: String,
    status: String,
    last_fired_at: Option(Int),
    next_fire_at: Int,
  )
}

pub fn get_schedule(id id: String) {
  let sql =
    "SELECT id, agent_id, skill_id, cron_expr, status, last_fired_at, next_fire_at
FROM schedules
WHERE id = ?"
  #(sql, [dev.ParamString(id)], get_schedule_decoder())
}

pub fn get_schedule_decoder() -> decode.Decoder(GetSchedule) {
  use id <- decode.field(0, decode.string)
  use agent_id <- decode.field(1, decode.optional(decode.string))
  use skill_id <- decode.field(2, decode.string)
  use cron_expr <- decode.field(3, decode.string)
  use status <- decode.field(4, decode.string)
  use last_fired_at <- decode.field(5, decode.optional(decode.int))
  use next_fire_at <- decode.field(6, decode.int)
  decode.success(GetSchedule(
    id:,
    agent_id:,
    skill_id:,
    cron_expr:,
    status:,
    last_fired_at:,
    next_fire_at:,
  ))
}

pub fn insert_schedule(
  id id: String,
  agent_id agent_id: Option(String),
  skill_id skill_id: String,
  cron_expr cron_expr: String,
  status status: String,
  next_fire_at next_fire_at: Int,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO schedules (id, agent_id, skill_id, cron_expr, status, next_fire_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamNullable(option.map(agent_id, fn(v) { dev.ParamString(v) })),
    dev.ParamString(skill_id),
    dev.ParamString(cron_expr),
    dev.ParamString(status),
    dev.ParamInt(next_fire_at),
    dev.ParamInt(created_at),
    dev.ParamInt(updated_at),
  ])
}

pub fn update_schedule_fire(
  last_fired_at last_fired_at: Option(Int),
  next_fire_at next_fire_at: Int,
  updated_at updated_at: Int,
  id id: String,
) {
  let sql =
    "UPDATE schedules SET last_fired_at = ?, next_fire_at = ?, updated_at = ?
WHERE id = ?"
  #(sql, [
    dev.ParamNullable(option.map(last_fired_at, fn(v) { dev.ParamInt(v) })),
    dev.ParamInt(next_fire_at),
    dev.ParamInt(updated_at),
    dev.ParamString(id),
  ])
}

pub fn deactivate_schedule(updated_at updated_at: Int, id id: String) {
  let sql =
    "UPDATE schedules SET status = 'inactive', updated_at = ?
WHERE id = ?"
  #(sql, [dev.ParamInt(updated_at), dev.ParamString(id)])
}

pub type ListDeployments {
  ListDeployments(
    id: String,
    agent_id: String,
    trigger_type: String,
    status: String,
  )
}

pub fn list_deployments() {
  let sql =
    "
SELECT id, agent_id, trigger_type, status
FROM deployments
WHERE status = 'active'
ORDER BY deployed_at DESC"
  #(sql, [], list_deployments_decoder())
}

pub fn list_deployments_decoder() -> decode.Decoder(ListDeployments) {
  use id <- decode.field(0, decode.string)
  use agent_id <- decode.field(1, decode.string)
  use trigger_type <- decode.field(2, decode.string)
  use status <- decode.field(3, decode.string)
  decode.success(ListDeployments(id:, agent_id:, trigger_type:, status:))
}

pub type GetActorRuns {
  GetActorRuns(
    id: String,
    status: String,
    trigger_type: String,
    result: String,
    duration_ms: Int,
    started_at: Int,
  )
}

pub fn get_actor_runs(agent_id agent_id: String, limit limit: Int) {
  let sql =
    "
SELECT id, status, trigger_type, COALESCE(result, '') as result, COALESCE(duration_ms, 0) as duration_ms, started_at
FROM runs
WHERE agent_id = ?
ORDER BY started_at DESC
LIMIT ?"
  #(
    sql,
    [dev.ParamString(agent_id), dev.ParamInt(limit)],
    get_actor_runs_decoder(),
  )
}

pub fn get_actor_runs_decoder() -> decode.Decoder(GetActorRuns) {
  use id <- decode.field(0, decode.string)
  use status <- decode.field(1, decode.string)
  use trigger_type <- decode.field(2, decode.string)
  use result <- decode.field(3, decode.string)
  use duration_ms <- decode.field(4, decode.int)
  use started_at <- decode.field(5, decode.int)
  decode.success(GetActorRuns(
    id:,
    status:,
    trigger_type:,
    result:,
    duration_ms:,
    started_at:,
  ))
}

pub fn insert_run(
  id id: String,
  agent_id agent_id: String,
  deployment_id deployment_id: Option(String),
  trigger_type trigger_type: String,
  trigger_source trigger_source: String,
  status status: String,
  started_at started_at: Int,
) {
  let sql =
    "INSERT INTO runs (id, agent_id, deployment_id, trigger_type, trigger_source, status, started_at)
VALUES (?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(agent_id),
    dev.ParamNullable(option.map(deployment_id, fn(v) { dev.ParamString(v) })),
    dev.ParamString(trigger_type),
    dev.ParamString(trigger_source),
    dev.ParamString(status),
    dev.ParamInt(started_at),
  ])
}

pub fn complete_run(
  status status: String,
  result result: Option(String),
  gas_used gas_used: Option(Int),
  duration_ms duration_ms: Option(Int),
  completed_at completed_at: Option(Int),
  id id: String,
) {
  let sql =
    "UPDATE runs SET status = ?, result = ?, gas_used = ?, duration_ms = ?, completed_at = ?
WHERE id = ?"
  #(sql, [
    dev.ParamString(status),
    dev.ParamNullable(option.map(result, fn(v) { dev.ParamString(v) })),
    dev.ParamNullable(option.map(gas_used, fn(v) { dev.ParamInt(v) })),
    dev.ParamNullable(option.map(duration_ms, fn(v) { dev.ParamInt(v) })),
    dev.ParamNullable(option.map(completed_at, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(id),
  ])
}

pub type GetActiveSession {
  GetActiveSession(id: String)
}

pub fn get_active_session() {
  let sql =
    "
SELECT id
FROM chat_sessions
WHERE status = 'active'
ORDER BY created_at DESC
LIMIT 1"
  #(sql, [], get_active_session_decoder())
}

pub fn get_active_session_decoder() -> decode.Decoder(GetActiveSession) {
  use id <- decode.field(0, decode.string)
  decode.success(GetActiveSession(id:))
}

pub fn create_session(
  id id: String,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO chat_sessions (id, status, created_at, updated_at)
VALUES (?, 'active', ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamInt(created_at),
    dev.ParamInt(updated_at),
  ])
}

pub fn save_chat_message(
  id id: String,
  session_id session_id: String,
  role role: String,
  content content: String,
  created_at created_at: Int,
) {
  let sql =
    "INSERT INTO chat_messages (id, session_id, role, content, created_at)
VALUES (?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(id),
    dev.ParamString(session_id),
    dev.ParamString(role),
    dev.ParamString(content),
    dev.ParamInt(created_at),
  ])
}

pub type GetChatMessages {
  GetChatMessages(id: String, content: String, role: String, created_at: Int)
}

pub fn get_chat_messages(session_id session_id: String) {
  let sql =
    "SELECT id, content, role, created_at
FROM chat_messages
WHERE session_id = ?
ORDER BY created_at ASC"
  #(sql, [dev.ParamString(session_id)], get_chat_messages_decoder())
}

pub fn get_chat_messages_decoder() -> decode.Decoder(GetChatMessages) {
  use id <- decode.field(0, decode.string)
  use content <- decode.field(1, decode.string)
  use role <- decode.field(2, decode.string)
  use created_at <- decode.field(3, decode.int)
  decode.success(GetChatMessages(id:, content:, role:, created_at:))
}
